runtime: python3.7
description: Checks for updates to my patent application
handler: lambda_handler.lambda_handler
code:
  s3_bucket: aseaman-lambda-functions
  s3_key_format: jobs/patent_number_{nonce}.zip
enabled: true
schedule_expressions:
  - cron(0 16 ? * MON,WED,FRI,SAT,SUN *)
  - cron(0 14 ? * TUE,THU *)
