runtime: python3.7
description: Checks for updates to my patent application
handler: lambda_handler.lambda_handler
code:
  s3_bucket: aseaman-lambda-functions
  s3_key_format: jobs/patent_number_{nonce}.zip
enabled: true
trigger_on_days:
  - Mon
  - Tue
  - Wed
  - Thu
  - Fri
  - Sat
  - Sun
