runtime: python3.7
description: Ensures that a salt level entry has been saved
handler: lambda_handler.lambda_handler
code:
  s3_bucket: aseaman-lambda-functions
  s3_key_format: jobs/salt_level_entry_checker_{nonce}.zip
enabled: false
schedule_expressions:
  - cron(0 18 ? * * *)
