runtime: python3.9
description: Triggered on new high scores in aseaman-public-bucket
handler: lambda_handler.lambda_handler
code:
  s3_bucket: aseaman-lambda-functions
  s3_key_format: jobs/mame_high_score_{nonce}.zip
enabled: false
trigger_bucket: aseaman-public-bucket
trigger_prefix: hi
