runtime: python3.7
description: Checks to see if my traffic ticket is in the system
handler: lambda_handler.lambda_handler
code:
  s3_bucket: aseaman-lambda-functions
  s3_key_format: jobs/traffic_ticket_{nonce}.zip
enabled: false
schedule_expressions:
  - cron(0 16 ? * MON,TUE,WED,THU,FRI,SAT,SUN *)
